#!/usr/bin/env bash
set -euo pipefail
# Step 54 patch: adds Spiti, Burhi Gandak, Jhelum via a new HydroRIVERS-based tracing
# pipeline (scripts/hydrorivers-tracer/) for rivers OSM/govt-shapefile sourcing missed.
# rivers.pmtiles is NOT regenerated by this script (needs the multi-hundred-MB
# HydroRIVERS shapefile + tippecanoe, not fresh-clone-reproducible) -- it ships as a
# separate binary alongside this patch script. Copy it into place manually:
#   cp rivers.pmtiles public/tiles/rivers.pmtiles

echo "Step 54: adding spiti, burhi-gandak, jhelum river detail files + tracer scripts"

mkdir -p public/data/rivers scripts/hydrorivers-tracer

if [ ! -f public/data/rivers/spiti.json ]; then
cat > public/data/rivers/spiti.json << 'RIVER_EOF'
{
  "id": "spiti",
  "name": "Spiti",
  "aliases": [],
  "local_names": { "hi": "स्पीति" },
  "basin": "indus-basin",
  "type": "tributary",
  "drainage_type": "himalayan",
  "seasonal_type": "perennial",
  "origin_type": "glacial",
  "stream_order": 5,
  "wikimedia_image_id": null,
  "source": {
    "name": "Kunzum Range glaciers, near Kunzum Pass",
    "state": "himachal-pradesh",
    "altitude_m": 4590,
    "coordinates": [77.6625, 32.61458]
  },
  "sink": {
    "name": "Confluence with the Sutlej at Khab Sangam",
    "type": "river",
    "location": "Khab, Kinnaur district, Himachal Pradesh, India",
    "coordinates": [78.6438, 31.7997]
  },
  "length_km_india": 182,
  "length_km_total": 182,
  "basin_area_total_km2": null,
  "basin_area_india_km2": null,
  "states_flows_through": ["himachal-pradesh"],
  "basin_states": ["himachal-pradesh"],
  "tributaries": { "left": [], "right": [] },
  "distributaries": [],
  "protected_area_ids": [],
  "navigable": false,
  "transnational": false,
  "transnational_countries": [],
  "significance": ["irrigation"],
  "notable_city_ids": [],
  "upsc_relevant": true,
  "did_you_know": [
    "The Spiti Valley — carved by this river — is a cold desert, receiving so little of the monsoon that it's often called \"Little Tibet.\"",
    "The Spiti meets the much larger, glacier-grey Sutlej at Khab Sangam, where the two rivers run visibly different colours before merging."
  ]
}
RIVER_EOF
  echo "  wrote public/data/rivers/spiti.json"
else
  echo "  public/data/rivers/spiti.json already present, skipping"
fi

if [ ! -f public/data/rivers/burhi-gandak.json ]; then
cat > public/data/rivers/burhi-gandak.json << 'RIVER_EOF'
{
  "id": "burhi-gandak",
  "name": "Burhi Gandak",
  "aliases": ["Sikrahna", "Sikrana"],
  "local_names": { "hi": "बूढ़ी गंडक" },
  "basin": "ganga-basin",
  "type": "tributary",
  "drainage_type": "himalayan",
  "seasonal_type": "perennial",
  "origin_type": "rain-fed",
  "stream_order": 5,
  "wikimedia_image_id": null,
  "source": {
    "name": "Someshwar hills, near Chautarwa Chaur, Bishambharpur",
    "state": "bihar",
    "altitude_m": 300,
    "coordinates": [84.40833, 27.35]
  },
  "sink": {
    "name": "Confluence with the Ganga",
    "type": "river",
    "location": "Near Khagaria, Bihar, India",
    "coordinates": [86.60694, 25.43389]
  },
  "length_km_india": 441,
  "length_km_total": 441,
  "basin_area_total_km2": 10150,
  "basin_area_india_km2": 10150,
  "states_flows_through": ["bihar"],
  "basin_states": ["bihar"],
  "tributaries": { "left": [], "right": [] },
  "distributaries": [],
  "protected_area_ids": [],
  "navigable": false,
  "transnational": false,
  "transnational_countries": [],
  "significance": ["frequent, severe flooding", "irrigation"],
  "notable_city_ids": [],
  "upsc_relevant": true,
  "did_you_know": [
    "Also called the Sikrahna in its upper reaches, the river takes the name Burhi (\"Old\") Gandak only after the Dhanauti river joins it near Motihari — the name marks it as an ancient, now-shifted channel of the neighbouring Gandak.",
    "The Burhi Gandak is rain-fed rather than glacier-fed, unlike the true Gandak it flows parallel to — making it far more prone to sudden, severe monsoon flooding across northern Bihar."
  ]
}
RIVER_EOF
  echo "  wrote public/data/rivers/burhi-gandak.json"
else
  echo "  public/data/rivers/burhi-gandak.json already present, skipping"
fi

if [ ! -f public/data/rivers/jhelum.json ]; then
cat > public/data/rivers/jhelum.json << 'RIVER_EOF'
{
  "id": "jhelum",
  "name": "Jhelum",
  "aliases": ["Vitasta", "Vyeth"],
  "local_names": { "hi": "झेलम" },
  "basin": "indus-basin",
  "type": "tributary",
  "drainage_type": "himalayan",
  "seasonal_type": "perennial",
  "origin_type": "spring-fed",
  "stream_order": 5,
  "wikimedia_image_id": null,
  "source": {
    "name": "Verinag Spring, base of the Pir Panjal range",
    "state": "jammu-and-kashmir",
    "altitude_m": 1876,
    "coordinates": [75.50417, 33.59792]
  },
  "sink": {
    "name": "Continues into Pakistan-administered Kashmir toward the Chenab",
    "type": "river",
    "location": "Line of Control near Uri, Baramulla district, Jammu and Kashmir, India",
    "coordinates": [74.0509, 34.0806]
  },
  "length_km_india": 228,
  "length_km_total": 725,
  "basin_area_total_km2": 51052,
  "basin_area_india_km2": null,
  "states_flows_through": ["jammu-and-kashmir"],
  "basin_states": ["jammu-and-kashmir"],
  "tributaries": { "left": [], "right": [] },
  "distributaries": [],
  "protected_area_ids": [],
  "navigable": true,
  "transnational": true,
  "transnational_countries": ["pakistan"],
  "significance": ["lifeline of the Kashmir Valley", "hydropower", "historic waterway (Srinagar's Dal Lake and Wular Lake)"],
  "notable_city_ids": [],
  "upsc_relevant": true,
  "did_you_know": [
    "The Jhelum is the westernmost of the five rivers that give Punjab (\"land of five waters\") its name, and the only one of the five that rises entirely within Indian territory rather than Tibet.",
    "Unlike its glacier-fed neighbours, the Jhelum rises from a spring — Verinag, at the foot of the Pir Panjal — and its waters pass through both Dal Lake and Wular Lake before leaving the Kashmir Valley."
  ]
}
RIVER_EOF
  echo "  wrote public/data/rivers/jhelum.json"
else
  echo "  public/data/rivers/jhelum.json already present, skipping"
fi

if [ ! -f scripts/hydrorivers-tracer/trace.js ]; then
cat > scripts/hydrorivers-tracer/trace.js << 'RIVER_EOF'
// Traces one named river through HydroRIVERS by walking NEXT_DOWN from the reach
// nearest a known source point to the reach nearest a known mouth/confluence point.
// HydroRIVERS carries no river names, so this is the only way to isolate a single
// river's course from the reach network without OSM/govt-shapefile coverage.
import fs from 'node:fs';

const network = JSON.parse(fs.readFileSync('build/hydrorivers-network.json', 'utf8'));

const GRID_DEG = 0.05; // ~5.5km cells — coarser than joinHydroRivers.js's 0.02, this is a point-nearest search not a broad-phase filter
const startGrid = new Map(); // keyed by reach START coord (headwater/waypoint candidates)

function key(lng, lat) {
  return `${Math.floor(lng / GRID_DEG)}_${Math.floor(lat / GRID_DEG)}`;
}
function addToGrid(grid, lng, lat, id) {
  const k = key(lng, lat);
  if (!grid.has(k)) grid.set(k, []);
  grid.get(k).push(id);
}

for (const id in network) {
  const r = network[id];
  const [slng, slat] = r.coords[0];
  addToGrid(startGrid, slng, slat, id);
}

function haversineKm(lng1, lat1, lng2, lat2) {
  const R = 6371;
  const toRad = (d) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}

// Waypoint anchoring needs a different heuristic than pure nearest-vertex: in flat floodplain
// terrain especially, a tiny disconnected field-drain fragment (upland ~10 km²) is very often
// closer to a query point than the actual named river's own channel passing nearby. Since a
// waypoint is always a place known to sit ON a real, substantial named river, among all
// candidates within radiusKm we pick the one with the largest upstream catchment (upland) —
// not the closest one — which reliably rejects these tiny false-positive fragments.
function nearestOnSubstantialChannel(grid, lng, lat, coordPicker, radiusKm = 15) {
  const cellRadius = Math.ceil(radiusKm / (GRID_DEG * 111)) + 1;
  const cx = Math.floor(lng / GRID_DEG);
  const cy = Math.floor(lat / GRID_DEG);
  let best = null;
  let bestUpland = -1;
  let bestDist = null;
  for (let dx = -cellRadius; dx <= cellRadius; dx++) {
    for (let dy = -cellRadius; dy <= cellRadius; dy++) {
      const ids = grid.get(`${cx + dx}_${cy + dy}`);
      if (!ids) continue;
      for (const id of ids) {
        const [clng, clat] = coordPicker(network[id]);
        const dist = haversineKm(lng, lat, clng, clat);
        if (dist > radiusKm) continue;
        const upland = network[id].upland ?? 0;
        if (upland > bestUpland) {
          bestUpland = upland;
          best = id;
          bestDist = dist;
        }
      }
    }
  }
  return best ? { id: best, distKm: bestDist, upland: bestUpland } : null;
}

// Reverse adjacency (nextDown -> incoming reach ids), built once, needed for upstream walk.
const upstreamOf = new Map();
for (const id in network) {
  const nx = network[id].next;
  if (nx && nx !== 0) {
    const key = String(nx); // NEXT_DOWN parses as a number; object keys from `for..in` are strings — normalize both sides
    if (!upstreamOf.has(key)) upstreamOf.set(key, []);
    upstreamOf.get(key).push(id);
  }
}

function stitch(path) {
  const coords = [];
  for (const id of path) {
    const c = network[id].coords;
    if (coords.length && coords[coords.length - 1][0] === c[0][0] && coords[coords.length - 1][1] === c[0][1]) {
      coords.push(...c.slice(1));
    } else {
      coords.push(...c);
    }
  }
  return coords;
}

/**
 * Anchors on a single unambiguous MID-RIVER waypoint — a town/village clearly on the named
 * river's own channel, away from both headwater divides (ambiguous — two valleys can share a
 * pass) and confluences (ambiguous for a tributary — the larger river being joined always has
 * more upstream catchment area, so a naive max-upland branch choice AT the confluence would
 * incorrectly follow the bigger river, not climb the tributary itself). Starting mid-channel
 * needs no branch decision at the confluence (we walk TO it downstream, already knowing which
 * reach we're on) and no branch decision at the source divide either, since forks encountered
 * while climbing are between the target river's own sub-tributaries, where max-upland (largest
 * contributing catchment = conventional main stem) is the correct rule.
 *
 * @param {[number,number]} waypointPt [lng, lat] — any unambiguous point clearly on the river's own channel
 * @param {[number,number]} mouthPt [lng, lat] — confluence with a larger river, or sea mouth
 * @param {object} opts
 * @param {number} opts.mouthToleranceKm - how close a reach END must be to mouthPt to count as arrival
 * @param {number} opts.minUpstreamAreaSkm - stop climbing once the best branch's catchment drops below this
 */
export function traceRiver(waypointPt, mouthPt, opts = {}) {
  const mouthToleranceKm = opts.mouthToleranceKm ?? 6;
  const minUpstreamAreaSkm = opts.minUpstreamAreaSkm ?? 0;

  const anchor = nearestOnSubstantialChannel(startGrid, waypointPt[0], waypointPt[1], (r) => r.coords[0]);
  if (!anchor) return { ok: false, reason: 'no reach found near waypoint' };

  // downstream walk from waypoint to mouth
  const downPath = [];
  let current = anchor.id;
  let downStop = null;
  for (let i = 0; i < 2000; i++) {
    const r = network[current];
    if (!r) {
      downStop = 'next_down reach missing from clipped network (crosses India border)';
      break;
    }
    downPath.push(current);
    // Primary stop condition: a confluence with a much larger river shows up as a huge single-step
    // jump in upstream catchment area — far sharper and more reliable than distance-to-mouth-point,
    // which can overshoot by exactly one reach onto the larger river's own channel (that reach's
    // end coordinate often still lands within tolerance of the named confluence point, since it's
    // the same location — silently inflating length/order with a foreign river's downstream reach).
    const nextReach = r.next && r.next !== 0 ? network[r.next] : null;
    if (nextReach && (nextReach.upland ?? 0) > (r.upland ?? 0) * 3 && (nextReach.upland ?? 0) - (r.upland ?? 0) > 500) {
      downStop = 'next reach belongs to a much larger river (confluence) — stopped before crossing onto it';
      break;
    }
    const [elng, elat] = r.coords[r.coords.length - 1];
    if (haversineKm(elng, elat, mouthPt[0], mouthPt[1]) <= mouthToleranceKm) {
      downStop = 'reached mouth point';
      break;
    }
    if (!r.next || r.next === 0) {
      downStop = 'next_down = 0 (terminal reach — sea or endorheic sink)';
      break;
    }
    current = r.next;
  }

  // upstream main-stem climb from the waypoint anchor
  const upPath = [];
  let node = anchor.id;
  let climbSteps = 0;
  while (climbSteps < 5000) {
    const incoming = upstreamOf.get(String(node));
    if (!incoming || incoming.length === 0) break;
    let best = incoming[0];
    for (const cand of incoming) {
      if ((network[cand].upland ?? 0) > (network[best].upland ?? 0)) best = cand;
    }
    if ((network[best].upland ?? 0) < minUpstreamAreaSkm) break;
    upPath.push(best);
    node = best;
    climbSteps++;
  }
  upPath.reverse();

  const fullPath = [...upPath, ...downPath];
  const coords = stitch(fullPath);
  const totalLenKm = fullPath.reduce((sum, id) => sum + network[id].len, 0);
  const maxOrd = fullPath.reduce((m, id) => Math.max(m, network[id].ord), 0);
  const headReach = fullPath[0];
  const [hLng, hLat] = network[headReach].coords[0];
  const tailReach = fullPath[fullPath.length - 1];
  const tailCoords = network[tailReach].coords;
  const [tLng, tLat] = tailCoords[tailCoords.length - 1];

  return {
    ok: true,
    anchorWaypointDistKm: Math.round(anchor.distKm * 10) / 10,
    downstreamStopReason: downStop,
    finalMouthDistKm: Math.round(haversineKm(tLng, tLat, mouthPt[0], mouthPt[1]) * 10) / 10,
    upstreamReachCount: upPath.length,
    downstreamReachCount: downPath.length,
    totalLenKm: Math.round(totalLenKm * 10) / 10,
    strahlerOrder: maxOrd,
    headwaterPt: [hLng, hLat],
    coords,
    reachIds: fullPath,
  };
}
RIVER_EOF
  echo "  wrote scripts/hydrorivers-tracer/trace.js"
else
  echo "  scripts/hydrorivers-tracer/trace.js already present, skipping"
fi

if [ ! -f scripts/hydrorivers-tracer/buildIndex.js ]; then
cat > scripts/hydrorivers-tracer/buildIndex.js << 'RIVER_EOF'
// One-off: parse the clipped HydroRIVERS geojson into a compact network index
// held in memory for scripts_wip/trace.js to require() via a shared cache file.
import fs from 'node:fs';

const SRC = 'build/hydrorivers-india-clip.geojson';
const OUT = 'build/hydrorivers-network.json';

console.log('Reading', SRC);
const raw = fs.readFileSync(SRC, 'utf8');
console.log('Parsing JSON (', (raw.length / 1e6).toFixed(0), 'MB )');
const d = JSON.parse(raw);

const reaches = {};
for (const f of d.features) {
  const p = f.properties;
  const g = f.geometry;
  const coords = g.type === 'MultiLineString' ? g.coordinates[0] : g.coordinates;
  reaches[p.HYRIV_ID] = {
    next: p.NEXT_DOWN,
    len: p.LENGTH_KM,
    ord: p.ORD_STRA,
    main: p.MAIN_RIV,
    upland: p.UPLAND_SKM, // upstream catchment area — used to pick the main-stem branch at forks
    coords: coords.map(([lng, lat]) => [Math.round(lng * 1e5) / 1e5, Math.round(lat * 1e5) / 1e5]),
  };
}

console.log('Reaches:', Object.keys(reaches).length);
fs.writeFileSync(OUT, JSON.stringify(reaches));
console.log('Wrote', OUT, (fs.statSync(OUT).size / 1e6).toFixed(0), 'MB');
RIVER_EOF
  echo "  wrote scripts/hydrorivers-tracer/buildIndex.js"
else
  echo "  scripts/hydrorivers-tracer/buildIndex.js already present, skipping"
fi

if [ ! -f scripts/hydrorivers-tracer/README.md ]; then
cat > scripts/hydrorivers-tracer/README.md << 'RIVER_EOF'
# HydroRIVERS tracer

Used to add rivers not covered by OSM/govt-shapefile matching (§4.9's spec list is ~105
rivers; 85 shipped from OSM/govt sourcing — the rest need HydroRIVERS since OSM has no
name-matched geometry for them).

## Requirements
- `HydroRIVERS_v10_as.shp` (+ .shx/.dbf/.prj) from hydrosheds.org/products/hydrorivers,
  staged at `build/raw/hydrorivers/` (gitignored, re-supply each session — see
  `scripts/joinHydroRivers.js` for the same requirement on the existing 85's pipeline).
- `tippecanoe` + `tile-join` (apt-get install -y tippecanoe on Debian/Ubuntu; not available
  on Windows — sandbox-only, matches the project's existing tippecanoe precedent).

## Pipeline
1. Clip to India: `pnpm exec mapshaper build/raw/hydrorivers/HydroRIVERS_v10_as.shp -proj wgs84 -clip bbox=68,6,98,36 -o build/hydrorivers-india-clip.geojson format=geojson`
2. Build the compact network index: `node scripts/hydrorivers-tracer/buildIndex.js` → `build/hydrorivers-network.json`
3. For each river, research ONE unambiguous mid-river waypoint (a town clearly on the
   channel — NOT the source, which is ambiguous near passes/divides where two valleys can
   share a headwater ridge, and NOT the confluence, which is ambiguous for a tributary since
   the larger river being joined always has more catchment area) and the mouth/confluence
   point, then: `import { traceRiver } from './trace.js'; traceRiver([lng,lat] /* waypoint */, [lng,lat] /* mouth */)`
4. Sanity-check `totalLenKm` and `strahlerOrder` against a literature reference before
   trusting the result — HydroRIVERS' static-DEM network is unreliable in flat floodplain
   and especially tidal/deltaic terrain (see Rupnarayan case below).

## Known limitations (found via real tracing, not theoretical)
- **Flat floodplain terrain**: naive nearest-vertex matching finds tiny disconnected
  field-drain fragments (~10 km² catchment) closer to a query point than the actual named
  river passing nearby. Fixed via `nearestOnSubstantialChannel()` — picks the
  largest-catchment reach within radius, not the closest one.
- **Confluences**: the downstream walk can overshoot by exactly one reach onto the larger
  river's own channel before a distance-tolerance check catches it (that reach's end
  coordinate is often still within tolerance of the confluence point, since it's the same
  location). Fixed via a catchment-jump detector (>3x and >500 km² single-step jump = stop
  before crossing).
- **Tidal/deltaic confluence zones** (e.g. Rupnarayan, which converges with the Hooghly and
  Damodar in a maze of tidal channels near Geonkhali): the network's own topology breaks
  down here — even the largest nearby reach can dead-end (`next=0`) with an implausibly
  large catchment value (indicating it's actually merged/shared tidal-creek data, not a
  single river's channel). This is a genuine HydroRIVERS limitation in this terrain type,
  not a bug — needs manual/OSM sourcing instead, same as the original 85's flagged rivers.

## Output → shipping a new river
`traceRiver()` returns `{ coords, totalLenKm, strahlerOrder, ... }`. To ship:
1. Author `public/data/rivers/{id}.json` (RiverDetail schema) — `length_km_india` should
   match the traced geometry's length exactly (the project's convention, confirmed against
   the existing 85: it's a measured length of the shipped line, not a quoted reference figure).
2. Append an entry to `public/data/rivers-index.json` (RiverIndexEntry schema) — `bounds` is
   the traced coords' bbox.
3. Re-extract the CURRENT `rivers.pmtiles` at full maxzoom fidelity, per-river-bbox-scoped
   (NOT `scripts/extractRiversFromPmtiles.mjs`'s whole-India z11 probe — that's simplified/
   lossy, fine for a quick look but would visibly downgrade the existing rivers' line
   quality if used as the rebuild source). Append the new river's feature(s), assign fresh
   sequential top-level numeric `id`s to every feature, rebuild via tippecanoe with the
   exact command from Spec_file.md §4.9 (`--include=id --include=stream_order`, z4–z14).
4. Regenerate `rivers-id-map.json` (riverId → array of that river's numeric feature ids).
RIVER_EOF
  echo "  wrote scripts/hydrorivers-tracer/README.md"
else
  echo "  scripts/hydrorivers-tracer/README.md already present, skipping"
fi

if grep -q '"id": "spiti"' public/data/rivers-index.json; then
  echo "  rivers-index.json already has spiti/burhi-gandak/jhelum, skipping append"
else
cat > ./_step54_append.mjs << 'APPEND_EOF'
import fs from 'node:fs';
const idx = JSON.parse(fs.readFileSync('public/data/rivers-index.json', 'utf8'));
idx.push({"id":"spiti","name":"Spiti","local_name_hi":"स्पीति","basin":"indus-basin","length_km_india":182,"basin_area_india_km2":null,"drainage_type":"himalayan","stream_order":5,"seasonal_type":"perennial","origin_type":"glacial","navigable":false,"transnational":false,"states":["himachal-pradesh"],"aliases":[],"bounds":[77.6625,31.80625,78.64375,32.61458]});
idx.push({"id":"burhi-gandak","name":"Burhi Gandak","local_name_hi":"बूढ़ी गंडक","basin":"ganga-basin","length_km_india":441,"basin_area_india_km2":10150,"drainage_type":"himalayan","stream_order":5,"seasonal_type":"perennial","origin_type":"rain-fed","navigable":false,"transnational":false,"states":["bihar"],"aliases":["Sikrahna","Sikrana"],"bounds":[84.39792,25.47708,86.57292,27.35]});
idx.push({"id":"jhelum","name":"Jhelum","local_name_hi":"झेलम","basin":"indus-basin","length_km_india":228,"basin_area_india_km2":null,"drainage_type":"himalayan","stream_order":5,"seasonal_type":"perennial","origin_type":"spring-fed","navigable":true,"transnational":true,"states":["jammu-and-kashmir"],"aliases":["Vitasta","Vyeth"],"bounds":[74.04792,33.56875,75.50417,34.37708]});
fs.writeFileSync('public/data/rivers-index.json', JSON.stringify(idx, null, 2) + '\n');
APPEND_EOF
  node ./_step54_append.mjs
  rm ./_step54_append.mjs
  echo "  appended spiti/burhi-gandak/jhelum to rivers-index.json"
fi

cat > public/data/rivers-id-map.json << 'IDMAP_EOF'
{"indus":[1],"chenab":[2],"ravi":[3],"beas":[4],"sutlej":[5],"zanskar":[6],"shyok":[7],"ganga":[8],"bhagirathi":[9],"alaknanda":[10],"yamuna":[11],"chambal":[12],"banas":[13],"kali-sindh":[14],"parbati":[15],"betwa":[16],"ken":[17],"son":[18],"gomti":[19],"ghaghra":[20],"sarda":[21],"gandak":[22],"kosi":[23],"mahananda":[24],"damodar":[25],"hooghly":[26],"barakar":[27],"ajay":[28],"brahmaputra":[29],"lohit":[30],"subansiri":[31],"kameng":[32],"manas":[33],"teesta":[34],"rangeet":[35],"torsa":[36],"jaldhaka":[37],"barak":[38],"kopili":[39],"mahanadi":[40],"brahmani":[41],"baitarani":[42],"subarnarekha":[43],"vamsadhara":[44],"nagavali":[45],"godavari":[46],"krishna":[47],"tungabhadra":[48],"bhima":[49],"musi":[50],"manjira":[51],"indravati":[52],"pranhita":[53],"wainganga":[54],"wardha":[55],"kaveri":[56],"amaravathi":[57],"kabini":[58],"hemavathi":[59],"shimsha":[60],"arkavathi":[61],"bhavani":[62],"palar":[63],"ponnaiyar":[64],"vellar":[65],"vaigai":[66],"narmada":[67],"tapi":[68],"mahi":[69],"sabarmati":[70],"periyar":[71],"bharathapuzha":[72],"pamba":[73],"kallada":[74],"sharavati":[75],"zuari":[76],"mandovi":[77],"ulhas":[78],"kali-karnataka":[79],"netravati":[80],"aghanashini":[81],"damanganga":[82],"vaippar":[83],"luni":[84],"ghaggar-hakra":[85],"spiti":[86],"burhi-gandak":[87],"jhelum":[88]}
IDMAP_EOF
echo "  wrote public/data/rivers-id-map.json (full regenerate — matches rivers.pmtiles feature ids exactly)"

echo ""
echo "NOTE: public/tiles/rivers.pmtiles must be replaced manually (binary, not embedded here):"
echo "  cp rivers.pmtiles public/tiles/rivers.pmtiles"
echo ""

pnpm install --frozen-lockfile

cat > ./_step54_validate.mjs << 'VALIDATE_EOF'
import { RiverDetail, RiverIndexEntry } from './scripts/schemas.js';
import fs from 'node:fs';
for (const id of ['spiti', 'burhi-gandak', 'jhelum']) {
  RiverDetail.parse(JSON.parse(fs.readFileSync(`public/data/rivers/${id}.json`, 'utf8')));
}
const idx = JSON.parse(fs.readFileSync('public/data/rivers-index.json', 'utf8'));
for (const e of idx) RiverIndexEntry.parse(e);
console.log('schema validation ok:', idx.length, 'rivers-index entries');
VALIDATE_EOF
node ./_step54_validate.mjs
rm ./_step54_validate.mjs

pnpm exec astro check
pnpm build
echo "Step 54 patch complete."
